### PR TITLE
Adapt CI for changes in HelenOS/harbours#1

### PR DESCRIPTION
**Pull request by le-jzr**
This is a "best effort attempt" on my part. Not sure how successful it is.

### CODE REVIEW

**Comment by vhotspur** [comment]
I think this bypasses the fetch phase of CI where all tarballs (of ported software) are downloaded and then shared by all builds. It is not a vital feature but it speeds up the builds a bit and why to download the same tarball 15 times.

**Comment by le-jzr** [comment]
Oops, forgot about this one. I tidied up whitespace changes and I'm going to merge this as well.
I don't see how this change can affect the fetch phase. Maybe I'm missing something, but I think let's let it run once or twice, and if there turns out to be a problem, I'll give it more attention.

**Comment by le-jzr** [comment]
Oh, right, I forgot I can just run it locally. You're right, the fetch is broken. I'll fix it asap.

**Comment by le-jzr** [comment]
Fixed in harbours.

**Pull request merged**
